### PR TITLE
fix Japanese translation

### PR DESCRIPTION
**Pull request by incisakura**

### CODE REVIEW

**Comment by Akkariiin** [comment]
thanks for your work~~

**Comment by incisakura** [comment]
Σ(´∀｀；)～

**Comment by Akkariiin** [comment]
thank you ~~~
We need more people like you~

**Comment by incisakura** [comment]
The former translation was almost translated by machine,or I won't do this.（（

**Comment by incisakura** [comment]
Maybe I deleted it by accident,sorry(

**Pull request merged**
